config/routes.rb
TaskManager::Application.routes.draw do
  devise_for :users
  resources :users , only:[:show , :index]

  resources :projects
  
  root 'static_pages#home'

  

  

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_and_belongs_to_many :users
  has_many :user_stories , dependent: :destroy
  accepts_nested_attributes_for :user_stories, reject_if: proc { |attributes| attributes['title'].blank? } , :allow_destroy => true

end

app/models/projects_user.rb
class ProjectsUser < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user_stories
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true

  has_attached_file :photo, :styles => { :small => "150x150>" },
                  :url  => "/assets/images/users/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/images/users/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png' , 'image/gif']

  has_and_belongs_to_many :projects
end

app/models/user_project_relation.rb
class UserProjectRelation < ActiveRecord::Base
	belongs_to :user, class_name: "User"
    belongs_to :project, class_name: "Project"
    validates :user_id, presence: true
    validates :project_id, presence: true
end

app/models/user_story.rb
class UserStory < ActiveRecord::Base
	belongs_to :projects
	has_many :tasks , dependent: :destroy

    accepts_nested_attributes_for :tasks, reject_if: proc { |attributes| attributes['descreption'].blank? } , :allow_destroy => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path current_user
  end

  protected

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super # Use the default one
    end
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :deny_to_visitors

	def new
		@project = Project.new 
    2.times do
       @user_story = @project.user_stories.build
       @user_story.tasks.build 
    end
	end

	def create
    if (@project = current_user.projects.create!(project_params) )
      flash[:success] = "Project created!"
      redirect_to project_path @project
    else
      #@feed_items = []
      #render 'static_pages/home'
    end
	end

  def show
    @project = Project.find(params[:id])
    @users = @project.users.paginate(page: params[:page])
  end
  
  def index
    @projects = Project.paginate(page: params[:page])
  end

  private
	def deny_to_visitors
      redirect_to root_path unless user_signed_in?
    end

    def project_params
    	params.require(:project).permit(:title , :descreption , user_stories_attributes: [:title , tasks_attributes: :descreption] )
    end
end

app/controllers/projects_user_controller.rb
class ProjectsUserController < ApplicationController
  def create
    # @project = Project.find(params[:projects_users][:project_id])
    # current_user.Projects_users.create!(user_id: project.id)
  end

  def destroy

  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	def index
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end
end

app/controllers/user/SessionsController.rb
class User::SessionsController < Devise::SessionsController
	def index
	end
end

app/controllers/user/parameter_sanitizer.rb
class User::ParameterSanitizer < Devise::ParameterSanitizer
  def sign_up
    default_params.permit(:first_name , :last_name , :email , :password , :password_confirmation , :photo )
  end
end

app/controllers/user/sessioms.rb
class SessionsController 
	def index
	end
end

app/controllers/user_project_relation_controller.rb
class UserProjectRelationController < ApplicationController
	def create 
	end

	def destroy
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		
	end

	def show
		@user =  User.find(params[:id])
		@projects = @user.projects.paginate(page: params[:page])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper 
	# def link_to_remove_fields(name,f)
	# 	f.hidden_field(:_destroy) + link_to_function(name , "remove_fields(this)")
	# end

 #    def link_to_add_fields(name, f, association)
    	
	#     new_object = f.object.class.reflect_on_association(association).klass.new
	#     fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	#       render(association.to_s.singularize + "_field", :f => builder)
	#     end
	#     link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
 #    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/projects_user_helper.rb
module ProjectsUserHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_project_relation_helper.rb
module UserProjectRelationHelper
end

app/views/projects/_project.html.haml
%li
  = link_to project.title , project

app/views/projects/_task_field.html.haml
%p.fields  
  = f.label :descreption
  = f.text_area :descreption
  = f.link_to_remove "Remove"


//  = f.link_to_add "Add task", :tasks

app/views/projects/_user_story_field.html.haml
.fields
  %p
    %h2 User Stories :
    = f.label :title , "User Story :"
    = f.text_field :title
    = f.link_to_remove "Remove"
 
    %h4 Tasks :
    = f.fields_for :tasks do |builder|
      = render 'task_field', :f => builder
    = f.link_to_add "Add Task", :tasks
    

app/views/projects/index.html.haml
%h1 All Projects

= render @projects

app/views/projects/new.html.haml
.NewProject
  %h1 New Project
  
  = nested_form_for( @project ) do |f|
    = f.label :title
    = f.text_field :title
    %br
    %br

    = f.label :descreption
    = f.text_area :descreption
    %br

    = f.fields_for :user_stories do |builder|
      = render 'user_story_field', :f => builder
    // = link_to_add_fields "Add User Story", f, :user_stories 
    = f.link_to_add "Add User Story", :user_stories
    %br

    = f.submit "Create New Project" , class: "btn btn-medium btn-primary"

    %h3 Select Assigned Users :
    = select_tag :user, options_from_collection_for_select(User.all, :id, :first_name), :onchange => 'add_new_user()' , :prompt => "Please select user"
    %br 
    
    /- itemlist = User.find(:all,:select => 'first_name')
    //= select_tag :user , options_for_select(users , { :prompt => "Select a Country"}) 
    
    / # = @user = User.pluck(:first_name)
    / = f.select :users, @user    
    // = collection_select :user, User.find(:all), :id, :first_name,{ :prompt => "Select a Country"}
    

    


  

app/views/projects/show.html.haml
%h1 you are in show project 
%h1= params[:id]

- if @project.user_stories.any?
  %h3 User Stries :
  %ol
    - @project.user_stories.each do |user_story|
      %li= user_story.title

      - if user_story.tasks.any?
        %h1 Tasks :
        %ol
          - user_story.tasks.each do |task|
            %li= task.descreption

- if @users.any? 
  %ol.users
    = render @users

app/views/static_pages/home.html.haml
- if !current_user.nil? 
  = current_user.first_name << " "<< current_user.last_name 
  = image_tag current_user.photo.url(:small)
  

app/views/static_pages/test.html.haml
%h1 Test page

app/views/users/_user.html.haml
%li
  = link_to user.first_name << " " << user.last_name , user

app/views/users/index.html.haml
%h1 Hello from index

= will_paginate @users

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.haml
%h2
  = @user.first_name << " " << @user.last_name

= image_tag @user.photo.url(:small)
%br
%br

-if @user == current_user
  = link_to "New Project" , new_project_path , class: "btn btn-large btn-primary"
  %br
  %br
  
  - if @projects.any? 
    %ol.projects
      = render @projects